<?php

namespace BrightSoft\StorageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileTypeRepository extends EntityRepository
{
}
